site_name: Flight DIY

site_description:

site_author: Gavin Gao

site_url:

theme: 
  name: readthedocs # readthedocs material
  nav_style: light
  # language: 'zh'
  # palette:
  #   primary: 'light blue'
  #   accent: 'indigo' 
  feature:
    tabs: true

markdown_extensions:
  - toc:
      permalink: true # "#"
      # baselevel: 5
      separator: "_"
  - admonition
  - footnotes
  - meta
  - def_list
  - codehilite:
      guess_lang: false
      linenums: false
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.snippets
  - pymdownx.arithmatex
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.tilde        
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_png
  - pymdownx.tasklist:
      custom_checkbox: true

plugins:
  - search
        
nav:
  - Home: 'index.md'

  - Hardware & Software Config:
    - Hardware: 'hsw_cfg/hardware.md'
    - Software: 'hsw_cfg/software.md'
    - Config & Debug: 'hsw_cfg/config_debug.md'
  
  - Simulation: 
    - ROS with Gazebo Simulation: 'simulation/ros_gazebo.md'

  - Development:
    - Development PX4: 'development/dev_px4.md'

  - Credential:
    - Pilot License: 'credential/pilot_license.md'
  
  - Course:
    - Shenlan: 'course/shenlan.md'
